### ISSUE TITLE
"Could not determine executable" when running npx command using Node 15

### ISSUE THREAD

**Issue by crevulus** [mediamonks/porter#10] opened 2021-03-03 12:36 UTC
In the image below, you can see the error that was thrown in my terminal.

Tried to run an npx command to use the react skeleton and received `Could not determine executable to run`.

Checked my npm version: `15`

Tried running npx commands for `react-base` and `vue`, but got the same error.

Switched to `node 14`

Then able to use all npx commands successfully.

![Screenshot 2021-03-03 at 13 30 44](https://user-images.githubusercontent.com/50107046/109806611-2d440a00-7c25-11eb-9913-81faaf159a3a.png)

**Comment by psimk** [comment] 2021-03-03 13:54
Duplicate of https://github.com/mediamonks/porter/issues/8

**Closed by psimk** 2021-03-03 13:54 UTC
